### ISSUE TITLE
show throws sectormismatch

### ISSUE THREAD

**Issue by maartenvd** [Jutho/TensorKit.jl#20] opened 2019-11-10 14:56 UTC
The following tensor
`t = TensorMap(rand,ComplexF64,U₁Space(0=>12, 1=>0, -1=>12, -2=>12),(U₁Space(0=>1)' ⊗ U₁Space(0=>12, 1=>12, -1=>12)));`

can be created, but when trying to see it's contents I get a sectormismatch. 

totally unrelated, but norm(t) works while norm(t') fails because norm() is defined on general abstract tensormaps, while it assumes the layout of a normal tensormap. I think it should be something like (linalg.jl:133)

LinearAlgebra.norm(t::AdjointTensorMap{<:EuclideanSpace}, p::Real) = norm(t.parent,p);
LinearAlgebra.norm(t::TensorMap{<:EuclideanSpace}, p::Real) = ...

**Comment by Jutho** [comment] 2019-11-10 21:29
That's caused by the sector with degeneracy zero; I'll look into it.

**Comment by Jutho** [comment] 2019-11-11 11:30
Both should be fixed now.

**Closed by Jutho** 2019-11-11 11:30 UTC
